### ISSUE TITLE
\ini command doesn't work reliably

### ISSUE THREAD

**Issue by Triton171** [Triton171/dsa-cli#23]
In some situations, it seems like the /ini command (with the --all option) only retrieves a subset of the users it should apply to. It would be nice to be able to reproduce this bug. Maybe it has something to do with serenity cache weirdness?

**Comment by Smephite** [comment]
Occurred due to strange permission set up:

Roles (in hierarchy):

* `Anti` (View Channel: false)
* `mulmius` (View Channel: false)
* `DSA` (View Channel: true)
* `@everyone` (View Channel: false)

Problem was: `Anti` overwrote `DSA` thus the bot thought no permission was granted for members of `Anti`.

Problem was first solved by adding user permission to channel in question, later removing the negativ permission for `Anti` and `mulmius` fixed this in our case (either removing the role from channel permissions all together or just setting View Channel to neutral).

It seems like serenities permission handling is different from Discords as obviously in the pre-fix case `DSA` was able to see and write to the channel but serenity thought they were not able to.
