### ISSUE TITLE
Config does not update with update

### ISSUE THREAD

**Issue by Smephite** [Triton171/dsa-cli#4]
After update to newer version of the cli the config has to be populated manually with newly added options.

e.g. 

``Error while trying to retrieve config: missing field `max_name_length` at line 8 column 5``

``Error while trying to retrieve config: missing field `auto_update_dsa_data` at line 282 column 1``

``Error while trying to retrieve config: missing field `dsa_rules` at line 284 column 1``

**Comment by Triton171** [comment]
This was intentional, as the old config structure wasn't flexible enough. From now on, all changes to the Config should be backwards compatible though. The simplest way to do this, is adding new configuration fields as `Option(field)`.

To make it more consistent, it might make sense to make all config fields optional and provide reasonable defaults.
